-- MySQL Script generated by MySQL Workbench
-- qui 08 dez 2022 09:39:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaoficial` DEFAULT CHARACTER SET utf8 ;
USE `pizzaoficial` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaoficial`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaoficial`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `ndecasa` VARCHAR(10) NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_endereco_cliente_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `pizzaoficial`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaoficial`.`pizza` (
  `idPizza` INT NOT NULL AUTO_INCREMENT,
  `sabor` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `tamanho` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idPizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaoficial`.`pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `pizzaoficial`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzapedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaoficial`.`pizzapedida` (
  `idPizzaPedida` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `pedido_idPedido` INT NOT NULL,
  `pizza_idPizza` INT NOT NULL,
  PRIMARY KEY (`idPizzaPedida`),
  INDEX `fk_pizzapedida_pedido1_idx` (`pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_pizzapedida_pizza1_idx` (`pizza_idPizza` ASC) VISIBLE,
  CONSTRAINT `fk_pizzapedida_pedido1`
    FOREIGN KEY (`pedido_idPedido`)
    REFERENCES `pizzaoficial`.`pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizzapedida_pizza1`
    FOREIGN KEY (`pizza_idPizza`)
    REFERENCES `pizzaoficial`.`pizza` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;